### ISSUE TITLE
Issue for my team capstone space-travellers-hub

### ISSUE THREAD

**Issue by Mekuseo** [Mekuseo/Space-Travellers-Hub#21]
https://github.com/Mekuseo/Space-Travellers-Hub/projects/2
Hi Reviewer, There are 2 people in this team

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! For a team with `two` people - Number of cards in Backlog should be equal to `17` 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/223183246-dc1921d9-92a2-4e49-8485-6f9121bab499.png)

- [ ] [REQUIRED] Please `group tasks` shoud assigned, kindly assigne all members to `group tasks` 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/223183774-c8359a43-3caf-4b07-bcb6-e3442cf915dd.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
Hi 👋 team,

You have done a great job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646096-51e043e6-1884-4ace-a446-3068f22b6b6f.gif)

### To highlight

- The board is set 👍
- The PR title and description looks professional, with all the information 👍

## Required Changes ♻️
- [ ] As suggested by the previous reviewer, for a group of two people, the number of cards should equal 17.
- Currently you have 15, please add two more.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/52934128/223212685-f7126e55-e7c2-421c-8f87-8ed8a901c668.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
